server:
  port: 12023

spring:
  application:
    name: blog-sms
  jackson:    # 返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 47.106.240.86
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数

zhenzi:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 104813
  appSecret: 80660e02-6d38-4889-b056-f31cddf45614
